AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Send a daily headline from reddit via SMS.

Parameters: 
  PhoneNumber: 
    Type: String
    Description: The phone number recipient of the headline, in E.164 (e.g. +15555550100) format.
  UTCHour: 
    Type: String
    Default: 0
    Description: The hour at which to send the headline, in the UTC time zone.
  Subreddit: 
    Type: String
    Default: worldnews
    Description: The subreddit to get a top headline from.
          
Resources:
  HeadlineFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: headline.lambda_handler
      Runtime: python3.6
      Timeout: 5
      CodeUri: headline.py
      Environment:
        Variables:
          PHONE_NUMBER: !Ref PhoneNumber
          SUBREDDIT: !Ref Subreddit
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: !Join [' ', ['cron(0', !Ref UTCHour, '* * ? *)']]
      Policies:
       - SNSPublishMessagePolicy:
           TopicName: !GetAtt SNSTopic.TopicName
  SNSTopic:
    Type: "AWS::SNS::Topic"
    Properties: 
      DisplayName: RedditNews
      Subscription:
        -
          Endpoint: !Ref PhoneNumber
          Protocol: sms
